### ISSUE TITLE
 keyboard got freezed after lost internet connection

### ISSUE THREAD

**Issue by tshwangq** [rdesktop/rdesktop#37] opened 2016-04-08 06:51 UTC
Im using ubuntu with last version of rdesktop from a shell inside emacs.
steps to reproduction:
1. open a terminal window.
2.  emacs &
3. in emacs open a shell : M-x shell
4. inside emacs shell. call rdesktop 
5. after connected to remote desktop. close wifi
6. turn on wifi again.
7. cannot type an char in any window(browser, emacs, office anywhere).
   but mouse works.

thanks

**Comment by hean01-cendio** [comment] 2016-05-02 05:52
Duplicate of Issue #17

**Closed by hean01-cendio** 2016-05-02 05:52 UTC
