### ISSUE TITLE
“rdesktop” is not responding.

### ISSUE THREAD

**Issue by badfiles** [rdesktop/rdesktop#76] opened 2016-11-21 22:43 UTC
After switching to another window and returning back to rdesktop window,
the annoying gnome-shell window appears

> “rdesktop” is not responding.
> You may choose to wait a short while for it to continue or force the application to quit entirely.

The GNOME guys refuse to either disable the window, or make ping timeout configurable, or switch ESC behavior to close the alert instead of killing the app.

Most topics on the subject suggest I should search for a bug in an app, which makes it stop responding to pings.

Why would rdesktop stop responding?

**Comment by hean01-cendio** [comment] 2017-01-19 08:26
We have seen this before, and we need to investigate this bug further, due to it is not easily reproduced.

**Comment by uglym8** [comment] 2017-01-23 10:54
Any hints (OS, DE) for how it may be reproduced?
What mode rdesktop should be run in (e.g. fullscreen)?
What method was used to switch to another window?

**Comment by badfiles** [comment] 2017-01-23 12:57
I open a session regularly (no full screen), with pretty standard options (nothing fancy).
I switch to another window clicking on it's icon (taskbar extension), or using alt-tab, or using (I have no clue how to properly name it) the window overview mode (mouse pointer in the left top corner).
In my case window switching method has no impact on the outcome.

**Comment by uglym8** [comment] 2017-01-23 13:21
How long does it take to show this dialog?
Or it's shown right after you switch the window?
Is the outcome the same each time?

What distro do you use?
What version of rdesktop do you use?
What DE (desktop environment) do  you use?

I'm using i3 so I have to check this issue in the vm.
I could not reproduce this in CentOS 7 Gnome3/Mate using the rdesktop built from the latest git commit.

**Comment by badfiles** [comment] 2017-01-23 19:50
It happens approx. in 5 seconds after activating the rdesktop window, the delay is every time the same.
It does not happen at all, if the covering window is not expanded.

Ubuntu 16.10, gnome 3.22
rgesktop built from latest git.

**Comment by uglym8** [comment] 2017-01-24 11:01
Thank you for details alas I could not reproduce the issue.

Host: Ubuntu 16.10 gnome 3.22  (had to install it by hand as hashicorp virtualbox image hangs after mutating it to libvirt provider).

Steps taken so far:
1) start terminal and launch rdesktop -u username server_ipa -g 800x600
2) login to Windows TS
3) start libreoffice writer by  clicking on its icon (taskbar extension) and make sure its window is expanded
3) alt-tab several times from rdesktop to writer and back

Still no "“rdesktop” is not responding" window:(

Could you be so kind to provide the steps that worked for you, please?

**Comment by hean01-cendio** [comment] 2017-01-24 21:57
commit 2a6298ac63e9db24 introduces support for _NET_WM_PING. A desktop environment uses this protocol to check if applications are hanging and could then present and dialog with option to kill the process.

As mentioned earlier the misbehaviour is only seen a few times and i couldn't reproduce. Maybe this is a problem related to Wayland and Xserver layer ?

**Comment by hean01-cendio** [comment] 2017-01-24 22:10
Ok, i verified that i run wayland session using:

`loginctl show-session <sessionnumber> -p Type`

and could reproduce the issue with gnome-shell showing the dialog.

When @uglym8 tested in a virtual machine i assume the graphics fallbacked to an normal Xserver session which works as expected, eg. i haven't seen the problem once, using X11...

So this is probably a bug in X11 layer of Wayland, more investigation needed.

**Comment by hean01-cendio** [comment] 2017-01-24 22:53
I'm not able to reproduce the problem anymore, however i found a bug in the related code which was fixed in commit b292399. @badfiles , could you check if this commit fixes your problem ?

**Comment by uglym8** [comment] 2017-01-25 06:48
Yep, do remember about #17 and my thoughts  about the issue cause were (from most likely to less likely):
1) locking/network problems which make rdesktop block and not handling NET_WM_PING in timely manner
2) WM bug
3) X11 bug

But as we all know sometimes less likely things happen to occur:)
Completely forgot about Wayland. 
Great job BTW:)

**Comment by badfiles** [comment] 2017-01-25 18:47
@hean01-cendio, I confirm the problem is gone with the latest commit. Thank you and @uglym8 for being helpful.

**Comment by hean01-cendio** [comment] 2017-01-25 20:33
Very nice. Just need to very that this works  when network disappears to the rdp server so that the dialog is shown when expected before closing.

**Comment by hean01-cendio** [comment] 2017-01-25 21:40
Verified expected behaviour using an iptables rule to drop packets. After X seconds gnome-shell shows the dialog for force close the hung rdesktop. Closing.

**Closed by hean01-cendio** 2017-01-25 21:40 UTC
Labels: bug, help wanted
