### ISSUE TITLE
rdesktop entering an infinite resize loop

### ISSUE THREAD

**Issue by bogbert** [rdesktop/rdesktop#225] opened 2018-01-07 01:34 UTC
Hi,

since the arrival of the new resizing feature, I noticed that rdesktop enters an infinite resize loop if I launch it specifying the geometry as percentage with a high value.

For example, on a 2048x1152 display, running that command:

`rdesktop -v -g 99% ...`

gives:

```
Connecting to server using SSL...
Connection established using SSL.
Connection successful
Window resize detected, reconnecting to new size 2026x1100
Disconnecting...
Resize reconnect loop triggered, new size 2026x1100
Connecting to server using SSL...
Connection established using SSL.
Connection successful
Window resize detected, reconnecting to new size 2026x1100
Disconnecting...
Resize reconnect loop triggered, new size 2026x1100
Connecting to server using SSL...
Connection established using SSL.
Connection successful
Window resize detected, reconnecting to new size 2026x1100
Disconnecting...
Resize reconnect loop triggered, new size 2026x1100
Connecting to server using SSL...
[...]
```

I tried to understand what is happening, so I ran the same command line with xtrace and this is what I saw:

```
[...]
000:<:0028: 52: Request(1): CreateWindow depth=0x18 window=0x07400002 parent=0x00000147 x=0 y=0 width=2026 height=1140 border-width=0 class=InputOutput(0x0001) visual=0x0000011e value-list={background-pixel=0x00000000 border-pixel=0x00ffffff backing-store=NotUseful(0x00) override-redirect=false(0x00) colormap=0x07400001}
[...]
000:>:0038: Event ConfigureNotify(22) event=0x07400002 window=0x07400002 above-sibling=None(0x00000000) x=10 y=33 width=2026 height=1100 border-width=0 override-redirect=false(0x00)
000:>:0038: Event (generated) ConfigureNotify(22) event=0x07400002 window=0x07400002 above-sibling=None(0x00000000) x=1 y=25 width=2026 height=1100 border-width=0 override-redirect=false(0x00)
[...]
000:<:004a: 20: Request(12): ConfigureWindow window=0x07400002 values={width=2026 height=1140}
[...]
000:>:033f: Event ConfigureNotify(22) event=0x07400169 window=0x07400169 above-sibling=None(0x00000000) x=10 y=33 width=2026 height=1100 border-width=0 override-redirect=false(0x00)
000:>:033f: Event (generated) ConfigureNotify(22) event=0x07400169 window=0x07400169 above-sibling=None(0x00000000) x=1 y=25 width=2026 height=1100 border-width=0 override-redirect=false(0x00)
[...]
```

We can see that rdesktop creates the window with the size 2026x1140.
It then receives a ConfigureNotify event with the size 2026x1100. My guess here is that the window has been resized by my window manager (cinnamon) probably because it wants to reserve 52 pixels of the screen height for the task bar and the window's title bar, so it forces the window to a maximum height of 1100 pixels.
The event is processed by rdesktop in xwin.c where it sets g_pending_resize to true.
This triggers the exit of the rdp.c main loop, a disconnection, and a new loop in the while(1) loop of the main function of rdesktop.c
There, line 1242, ui_init_connection is called to figure out the size of the window.
The problem is that instead of keeping the new size (2026x1100), it computes the size using the `-g 99%` setting, and obtains again 2026x1140.
So later, rdesktop sends a ConfigureWindow request to set the window size to 2026x1140 again, causing the reception of a new ConfigureNotify event, etc ...

I don't understand the rdesktop code well enough to propose a proper fix, but for a temporary workaround I reset g_sizeopt to 0 at the end of ui_init_connection so that the `-g 99%` setting is used only during its first call.

**Comment by hean01-cendio** [comment] 2018-01-11 16:42
Hi, bug was reproducible and fix is included in PR #232

**Comment by nospam3159** [comment] 2018-01-11 19:15
I can reproduce a similar infinite resize loop even with #232. Connecting to a VirtualBox with  a different resolution than my local display gives:

```
UI(debug): ui_create_window() width = 1024, height = 768
UI(debug): ui_resize_window(), Changing window 1280x800 to match new session 800x600 size
UI(debug): xwin_process_events(), Window mapped with size 1280x800
UI(debug): xwin_process_events(), ConfigureNotify: session: 800x600, new window: 800x600 (adj: 800x600)
UI(debug): xwin_process_events(), ConfigureNotify: session: 800x600, new window: 1280x800 (adj: 1280x800)
UI(debug): xwin_process_events(), ConfigureNotify: session: 800x600, new window: 1280x800
Window resize detected, reconnecting to new size 1280x800
Resize reconnect loop triggered, new size 1280x800
UI(debug): ui_create_window() width = 1280, height = 800
UI(debug): ui_resize_window(), Changing window 1280x800 to match new session 800x600 size
UI(debug): xwin_process_events(), ConfigureNotify: session: 800x600, new window: 1280x800 (adj: 1280x800)
UI(debug): xwin_process_events(), ConfigureNotify: session: 800x600, new window: 1280x800
UI(debug): xwin_process_events(), Window mapped with size 1280x800
UI(debug): xwin_process_events(), ConfigureNotify: session: 800x600, new window: 800x600 (adj: 800x600)
UI(debug): xwin_process_events(), ConfigureNotify: session: 800x600, new window: 1280x800 (adj: 1280x800)
UI(debug): xwin_process_events(), ConfigureNotify: session: 800x600, new window: 1280x800
Window resize detected, reconnecting to new size 1280x800
```

I believe the  issue is a misconception of what XResizeWindow() does. As far as I can understand the API, the function doesn't (can't) in itself perform a resize. It merely triggers a XResizeRequestEvent which the window manager is free to deal with in any way it finds suitable. No guarantees are made that the exact resolution requested is honoured, thus the infinite loop when rdesktop insists on an unobtainable window size.

**Comment by hean01-cendio** [comment] 2018-01-12 08:17
> I can reproduce a similar infinite resize loop even with #232. Connecting to a VirtualBox with a different
> resolution than my local display gives. 

That log snippet explain this: your windows manager forces the use of specific window size and your server refuses to accept it and forces a specific session size that you your windows manager doesn't comply to which in its turn reproduces another resize again and again and again...

There is no wrong with how XResizeWindow() is used, its about the implementation and concept of "Dynamic session resize" which requires that at least one side can confirm to the other. In your special case ratpoision and virtualbox RDP server doesnt play well. What would you expect in this case ?

Maybe we need to look into an option to disable dynamic session resize for these special cases.

**Comment by CendioOssman** [comment] 2018-01-12 09:10
Can we detect this case and automatically disable the resize? Or at least break the loop somehow if we can detect we're fighting the window manager?

**Comment by nospam3159** [comment] 2018-01-12 09:51
If this was a problem with my window manager, the issue would not exist. I didn't find the use case with non-matching session and screen sizes important enough to file a bug for. Yet when I was made aware that someone else did file a bug, I started adding my input. The bug is easier to reproduce in tiling window managers but, as we noticed, it also occurs in other environments when the session size is larger than the window manager allows.

Please note that the point of conflict here is called XResizeRequestEvent. That's _request_, as in _please_. A client is in no position to demand the window manager to comply to it's wishes. The window manager does the right thing here when it prioritizes the user's preference or the limitations of the environment it operates under.

I would describe the issue as rdesktop keeping on requesting a resize again and again and again, even though all those requests are based on the same external state. My expectation would be that rdesktop only requests a resize when there is a new previously not handled reason to resize available to process.

Unfortunately I don't understand neither the code or the desired use case for dynamic resizing well enough to suggest how fix. Maybe rdesktop needs to start differentiate between session size and window size when RDPEDISP is unavailable? maybe it just needs to keep the state of which requests have been made in order to not redo them?

**Comment by uglym8** [comment] 2018-01-12 10:00
I can confirm that #232 fixes the issue (at least for me) on ArchLinux and i3 wm.

with rdesktop build from 85a558a9193f45af04242a7f1bbd74ea14b32aa9 the issue is (-g 99% and infinite resize loop) present.
with rdesktop build from current HEAD (1553760a1e796b78351d22047c796f1cd6c46e89) no such issue does exist.

**Comment by hean01-cendio** [comment] 2019-01-23 12:16
We believe that this issue is solved.

**Closed by hean01-cendio** 2019-01-23 12:16 UTC
Labels: awaiting reply, bug
