### ISSUE TITLE
SmartCard(warning): TS_SCardControl(), bogus smart card control code 0x00fd0028

### ISSUE THREAD

**Issue by trentasis** [rdesktop/rdesktop#233] opened 2018-01-12 12:43 UTC
Hi,

Detected with latest master branch an error when you try to insert some smartcard in the smartcard reader

SmartCard(warning): TS_SCardControl(), bogus smart card control code 0x00fd0028

**Comment by trentasis** [comment] 2018-01-12 12:47
error showed with keyboard cherryr SC K1000, and error appears when you insert some smartcard, not all, only smartcard that use safesign driver

SmartCard(warning): TS_SCardControl(), bogus smart card control code 0x00fd0028

**Comment by uglym8** [comment] 2018-01-12 17:28
Hi!
Sorry, but I doubt that this is the latest master as this warning was replaced in 87d8d12 (https://github.com/rdesktop/rdesktop/commit/87d8d123b81093ec8ce635e3c5009038e5a102f3#diff-92e289bf01abb35f501f99158d27604fL2143) (on Jan 26, 2017)
which was a year ago.

Does this error prevent you from using smartcard or just irritate you?

**Comment by trentasis** [comment] 2018-01-12 17:50
Hi,

error message is that appear in second message 
SmartCard(warning): TS_SCardControl(), bogus smart card control code 0x00fd0028

And appears when you insert smardcard and certificate is not showed, certificate not propagated and not usable 

What does it means this error? how to solve?

**Comment by trentasis** [comment] 2018-01-12 18:43
Sorry, what i atr and how can I obtain, smartcard is from safesign and error is reported only inserting smartcard  in the smartcard reader, no other action, If you givendetail what do you need I  can try to obtain

Thanks

**Comment by trentasis** [comment] 2018-01-18 19:29
Hi,

first thanks for your help.
1.- I don't know, pcsc_scan output:
./pcsc_scan
PC/SC device scanner
V 1.5.2 (c) 2001-2017, Ludovic Rousseau <ludovic.rousseau@free.fr>
Using reader plug'n play mechanism
Scanning present readers...
0: Cherry KC 1000 SC [KC 1000 SC] 00 00

Thu Jan 18 21:22:27 2018
 Reader 0: Cherry KC 1000 SC [KC 1000 SC] 00 00
  Card state: Card inserted,
  ATR: 3B BB 18 00 C0 10 31 FE 45 80 67 04 12 B0 03 03 00 00 81 05 3C

sh: ATR_analysis: not found
ATR_analysis '3B BB 18 00 C0 10 31 FE 45 80 67 04 12 B0 03 03 00 00 81 05 3C': Success

2.- Driver is safesign and application is a propietary, but issue is reported only when you insert smart card in the smartcard reader, before to interactuate with our application, when is trying to read smartcard, also before to make a login in windows rdp session, after to run rdesktop /smartcard server we receive:

SmartCard(warning): TS_SCardControl(), bogus smart card control code 0x00fd0028

**Comment by trentasis** [comment] 2018-01-22 18:46
Any news?

**Comment by uglym8** [comment] 2018-01-23 07:28
Hi @trentasis, 
Thank you for the provided info (ATR etc).
No news atm. 
I consider this to be of low priority due to the fact that it's merely a warning.
I do hope though to reproduce and fix this eventually.
Stay tuned:)

**Comment by uglym8** [comment] 2018-01-23 14:54
Judging by http://www.cherry.de/cid/keyboards_with_smart_card_reader_CHERRY_KC_1000_SC.htm?rdeLocationAttr=US&rdeLocaleAttr=en&switch=true 
your keyboard has an ability to enter PIN in the secure way therefore its builtin reader is Class 2 one
(according the https://docs.citrix.com/en-us/xenapp-and-xendesktop/7-14/secure/smart-cards.html)

We've already got a reported issue with Class 2/3 readers  (#75).

I'll try to find Class 2/3 reader to reproduce this issue.
Will report back any findings.

**Comment by trentasis** [comment] 2018-01-23 21:57
OK, thanks!

I think that you are on right, tried with other smart card reader with same smartcard and seems that in this case this error is not reproduced... Do you know what is the real impact with this cherry KC 1000, works or exist some restriction, I don't understand what is the issue...

**Comment by uglym8** [comment] 2018-01-25 18:34
Got Class 2 reader.
It turned out you don't even have to use Class 2/3 reader to get this warning.
Stay tuned:)

**Comment by uglym8** [comment] 2018-01-27 16:56
@trentasis, please check whether #238 fixes your issue.

**Comment by trentasis** [comment] 2018-01-31 21:37
Thanks
Ok, now I'm busy, I'll try to test in some days

**Comment by trentasis** [comment] 2018-02-05 22:31
Thanks, I'll try to test, now I'm little busy, but I'll try as soon as
possible


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-27 17:56 GMT+01:00 Alexander Zakharov <notifications@github.com>:

**Comment by uglym8** [comment] 2018-02-09 11:24
Resolving this as fixed by #238.

Reopen please if you're still experiencing any problems.

**Closed by uglym8** 2018-02-09 11:24 UTC
Labels: awaiting reply
