### ISSUE TITLE
Does not always show the username of the logged in user

### ISSUE THREAD

**Issue by joedborg** [rdesktop/rdesktop#16] opened 2015-11-23 16:46 UTC
The expected behaviour (which sometimes happens) is to see the currently logged in user within the initial login prompt.

For example, if I'm logged in as user "joe" on a Windows host "winhost" that I then RDP to using 

```
rdesktop winhost
```

I'd expect to see winhost\joe as the logged in user via rdesktop.  As mentioned, this is sometimes the case, but other times I get the domain and user for the Linux client.  I can't tell whether it's random, user or host dependant.
##

**Comment by hean01-cendio** [comment] 2017-01-25 00:58
It is not expected behaviour to get the login prompt with the logged on user (local consol) on the rdp server. Either way, this is nothing rdesktop can control as a username is always sent over to the rdp server. Closing issue due to it works as expected.

**Closed by hean01-cendio** 2017-01-25 00:58 UTC
Labels: wontfix
