### ISSUE TITLE
rdp redirect double authentication

### ISSUE THREAD

**Issue by bakoalex** [rdesktop/rdesktop#121] opened 2017-06-01 06:52 UTC
We are using a Windows Server 2008R2 terminal server farm. The farm is contains three nodes. Our operators are using Rasberry PI 3 with Raspbian OS (April 2017, kernel version: 4.4, PIXEL Desktop), and they are using rdesktop program to connecto to the terminal server farm. 

If you are redirected to a different node of the farm (RDP Redirect), you have to enter your credentials twice.

Is there any solution, or workaround to solve this problem?

**Comment by hean01-cendio** [comment] 2017-06-01 12:00
Duplicate of  issue #8.

**Closed by hean01-cendio** 2017-06-01 12:00 UTC
Labels: duplicate
