### ISSUE TITLE
Build on Debian Jessie

### ISSUE THREAD

**Issue by mkudlacek** [rdesktop/rdesktop#247] opened 2018-02-16 10:00 UTC
Hello,
 due to this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=763599 I tried to build the current rdesktop from sources. But I got stucked on the pkg-config and libxcursor detection:

```
root@auczdiskless:~/rdesktop-master# ./configure  --disable-credssp --disable-smartcard
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for X... libraries , headers
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... no
checking for pkg-config... /usr/bin/pkg-config
checking for library containing socket... none required
checking for library containing inet_aton... none required
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/modem.h usability... no
checking sys/modem.h presence... no
checking for sys/modem.h... no
checking sys/filio.h usability... no
checking sys/filio.h presence... no
checking for sys/filio.h... no
checking sys/strtio.h usability... no
checking sys/strtio.h presence... no
checking for sys/strtio.h... no
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking sysexits.h usability... yes
checking sysexits.h presence... yes
checking for sysexits.h... yes
checking for strip... strip
checking for OpenSSL directory... /usr
configure: WARNING: pkg-config not available, cannot check for xrandr
configure: WARNING: pkg-config not available, cannot check for xcursor

rdesktop requires libXcursor, install the dependency
```
The package pkg-config is installed:

```
root@auczdiskless:~/rdesktop-master# dpkg -l | grep pkg-config
ii  pkg-config                       0.28-1                       i386         manage compile and link flags for libraries
```

The ./configure first says it found it:

```
checking for pkg-config... /usr/bin/pkg-config
```

But later it says:

```
configure: WARNING: pkg-config not available, cannot check for xrandr
configure: WARNING: pkg-config not available, cannot check for xcursor
```

Since I also installed the libxcursor:

```
root@auczdiskless:~/rdesktop-master# dpkg -l | grep libxcursor
ii  libxcursor-dev:i386              1:1.1.14-1+deb8u1            i386         X cursor management library (development files)
ii  libxcursor1:i386                 1:1.1.14-1+deb8u1            i386         X cursor management library
```

I tried to fool the configure by changing the ```HAVE_XCURSOR=0``` to ```HAVE_XCURSOR=1```  on line 5212. Configure went fine but ```make``` ends up with:

```
xwin.o: In function `ui_create_cursor':
/root/rdesktop-master/xwin.c:3407: undefined reference to `XcursorImageCreate'
/root/rdesktop-master/xwin.c:3456: undefined reference to `XcursorImageLoadCursor'
/root/rdesktop-master/xwin.c:3457: undefined reference to `XcursorImageDestroy'
/root/rdesktop-master/xwin.c:3445: undefined reference to `XcursorImageCreate'
/root/rdesktop-master/xwin.c:3453: undefined reference to `XcursorImageDestroy'
```

And that's something I don't know how to handle. Probably it has to do something with package name ```libxcursor1``` instead of ```libxcursor```...

The reason I'm undergoing this is having both Windows Server 2003 and Windows Server 2008 R2 terminal servers in my infrastructure. The package from Jessie doesn't work with 2008R2 and the one from Stretch doesn't work with 2003... I know, ancient stuff.

Thanks for help in advance.

**Comment by uglym8** [comment] 2018-02-16 10:23
Hi!
ATM I don't have i686 laying around but could you verify that
````
 $ pkg-config --cflags --libs xcursor xrandr
````
produces meaningful output? 
i.e. something like:
````
-lXcursor -lXrandr
````

**Comment by mkudlacek** [comment] 2018-02-16 10:45
Sure thing Alex.

Output for xcursor:

```
# pkg-config --cflags --libs xcursor
-lXcursor
```

Output for xrandr:
```
# pkg-config --cflags --libs xrandr
Package xrandr was not found in the pkg-config search path.
Perhaps you should add the directory containing `xrandr.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xrandr' found
```

Ok, is the xrandr even installed?

```
# apt install xrandr
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package xrandr is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  x11-xserver-utils
```

Nope, so let's install the x11-xserver-utils:
```
# apt install x11-xserver-utils
Reading package lists... Done
Building dependency tree
Reading state information... Done
x11-xserver-utils is already the newest version.
```

Hmm... Any ideas?

**Comment by uglym8** [comment] 2018-02-16 10:48
Ok. 
I'll install 32-bit Jessie and see what I can do.
Stay tuned:)

**Comment by uglym8** [comment] 2018-02-16 12:33
I can't reproduce this issue on 32-bit Debian Jessie.
````
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 8.10 (jessie)
Release: 8.10
Codename: jessie
````

````
$ dpkg -l |grep pkg-config
ii pkg-config 0.28-1 i386 manage compile and link flags for libraries
```` 
Additionally I installed:
````
libxcursor-dev libpcsclite-dev libssl-dev
````

Verified with:
````
$ git clone https://github.com/rdesktop/rdesktop.git
$ cd rdesktop
$ ./bootstrap && configure --disable-credssp && make
````

**Comment by uglym8** [comment] 2018-03-11 08:01
Closing due to no reply

**Closed** 2018-03-11 08:01 UTC
Labels: awaiting reply

**Comment by sklprogs** [comment] 2018-09-15 01:34
Hi! I had the same problem. Looks like ./bootstrap should be rerun after installing all dependencies. BTW, it should be ./configure, not configure.

**Comment by bebbo** [comment] 2019-09-21 16:36
I also installed:
`sudo apt install gnutls-dev nettle-dev libtasn1-dev pkg-config`

**Comment by glennmichaelmejias** [comment] 2020-05-22 06:38
@bebbo you are the only 1 who saved us! i'm gonna call you a hero. Thanks!
